---
title: "p8105_hw6_ga2612"
author: "Lupe Antonio"
date: "12/1/2023"
output:
  github_document:
    toc: TRUE
---

```{r setup, include=FALSE, message = FALSE}
library(tidyverse)
```

## Problem 1

Create a city_state variable (e.g. “Baltimore, MD”), and a binary variable indicating whether the homicide is solved. Omit cities Dallas, TX; Phoenix, AZ; and Kansas City, MO – these don’t report victim race. Also omit Tulsa, AL – this is a data entry mistake. For this problem, limit your analysis those for whom victim_race is white or black. Be sure that victim_age is numeric.

```{r, message = FALSE}
#loading data
homicide_data <- read_csv('data_hw6/homicide_data.csv') %>%
  mutate(
    city_state = str_c(city, state, sep = ', '),
    resolution = case_when(
      disposition == 'Closed without arrest' ~ 'unsolved',
      disposition == 'Open/No arrest' ~ 'unsolved',
      disposition == 'Closed by arrest' ~ 'solved'),
    #making victime_age numeric
    victim_age = as.numeric(victim_age)) %>%
  #excluding cities
  filter(city_state != 'Dallas, TX',
         city_state != 'Phoenix, AZ',
         city_state != 'Kansas City, MO',
         city_state != 'Tulsa, AL',
        #filtering victim_race
        victim_race == 'White' | victim_race == 'Black')
```




